### ISSUE TITLE
优化冲突文档检测功能

### ISSUE THREAD

**Issue by Aiviokoo** [frostime/siyuan-dailynote-today#134]
- [x] #137
- [ ] #138

----

## 原 Issue

自动合并/或者提供手机端运行不自动建立日记的开关/或其他更好的方案
讨论见图
![D9AEF9AB69E7C1C68652B9C38135FFD5](https://github.com/frostime/siyuan-dailynote-today/assets/87182333/6b377397-a647-4c3e-b372-c89e696d7cf7)

**Comment by frostime** [comment]
- [ ] 为冲突页面增加自动合并功能
- [ ] 增加设置，允许在手机端不会自动创建日记

**Comment by frostime** [comment]
![image](https://github.com/frostime/siyuan-dailynote-today/assets/27268127/e8f8553e-09a7-4b85-ab0d-0b19c4d28e98)
