### ISSUE TITLE
docker思源 v2.9.4版本上设置无法保存

### ISSUE THREAD

**Issue by garrettzuo** [frostime/siyuan-dailynote-today#146]
在服务端搭建的docker思源 v2.9.4版本上的今日插件在配置无法保存配置，请问是问题还是需要进行额外的配置

**Comment by frostime** [comment]
您好，我这里没有 docker 的服务配置，所以只能在浏览器端测试一下。至少在客户端上没看到有什么错误。

可否请你打开开发者模式看一下日志的输出？今日笔记插件在设置发生更改的时候，会将插件设置保存到本地，并在浏览器端打印如下的日志：


![image](https://github.com/frostime/siyuan-dailynote-today/assets/27268127/85b8a7a6-8aa8-4eef-aacb-e6e9369d95ae)

你可以检查一下在更改设置的时候，控制台是否能正常打印日志，并截图发我看一下。

**Comment by garrettzuo** [comment]
修改当前是可以有保存，但是新开窗口或者刷新就配置就又回到默认了，看到控制台有报错输出
![关闭打开_20230707115500](https://github.com/frostime/siyuan-dailynote-today/assets/24801513/bff285d4-9675-4446-9289-8b201f1492b8)

**Comment by garrettzuo** [comment]
修改当前是可以有保存，但是新开窗口或者刷新就配置就又回到默认了，看到控制台有报错输出
![关闭打开_20230707115500](https://github.com/frostime/siyuan-dailynote-today/assets/24801513/bff285d4-9675-4446-9289-8b201f1492b8)

**Comment by frostime** [comment]
控制台报错不是插件的，你需要认准日志的来源
![image](https://github.com/frostime/siyuan-dailynote-today/assets/27268127/2417dcdd-3604-4b1b-82a5-b098267ef069)

我现在也搞不清楚你的情况，这是插件启动的标准流程

![image](https://github.com/frostime/siyuan-dailynote-today/assets/27268127/aeddc097-7500-4ae9-b48e-6a07c2428e79)


首先会尝试「读入配置文件: DailyNoteToday.json.txt」，然后为了防止处理设置项目有更新的情况会把读入的项目重新导出一次，也就你看到的「写入配置文件」。

目前我在客户端和客户端浏览器伺服上都没有看到异常，我后面会尝试自己搭建一个 docker 来测试一下的。你可以做以下尝试：

1. 检查日志看启动的时候读入的配置和你之前保存的是否一致（配置文件里的设置是英文的，不过辨识一下应该还是能看懂）
2. 问一下有没有别的用docker的和你遇到同样的问题
3. 如果你有技术条件，可以到 docker 挂载的思源目录下，查看 `主空间/data/storage/petal/siyuan-dailynote-today/DailyNoteToday.json.txt` 里面的文本内容，看是否随着插件设置的更改而变动。

**Comment by frostime** [comment]
有人让我建议把导图插件关了
![Uploading image.png…]()

**Comment by garrettzuo** [comment]
配置前后两次文件没有改动
![image](https://github.com/frostime/siyuan-dailynote-today/assets/24801513/14815871-1c15-4691-ac6b-f6d98f669c27)
是不是目录不对

**Comment by frostime** [comment]
我这里也搞了一个 docker ，但是似乎没有你出现的这个问题。

![setting](https://github.com/frostime/siyuan-dailynote-today/assets/27268127/b5566e6f-2555-481c-81b3-4fdac53110cf)

**Comment by frostime** [comment]
理论上讲 `/data/storage/petal/siyuan-dailynote-today` 这个目录是对的，但是你说没有写入更新。你可以试着在这个目录下运行这行命令：

```bash
watch -d -n 1 stat DailyNoteToday.json.txt
```

这行命令会实时监控文件的读写时间，你可以一边运行这个命令一边在思源中操作插件，看看设置的更新是否伴随着文件的读写。如果文件检测到了更新，这行命令显示更新：

![image](https://github.com/frostime/siyuan-dailynote-today/assets/27268127/db22eed4-ac7e-40c6-81ef-3ca9c248e713)

**Comment by garrettzuo** [comment]
https://www.pandazoo.top/#s/9cf9QPAw
你要不试试导入我的这个？

**Comment by frostime** [comment]
我这里导入了一下你的数据，但是依然可以正常保存。。
![image](https://github.com/frostime/siyuan-dailynote-today/assets/27268127/e3bf1888-76b6-4ab5-b58c-2bf17358ec4f)

这个就很难办了。。

**Comment by garrettzuo** [comment]
那就有理由怀疑是思源api访问了其他地方的网络资源，我这边的网络无法访问导致的，我这边的网络访问多少有些限制的

**Comment by frostime** [comment]
我觉得应该是网络限制问题。这里有个 disable 的什么 url。

![image](https://github.com/frostime/siyuan-dailynote-today/assets/27268127/0f25941f-7ca5-456d-bf84-5da64ff67040)

但问题是，别的插件应该也要用 saveData API 啊，难道只有今日笔记插件一个出现了无法保存的问题吗？

**Comment by frostime** [comment]
你的问题解决了吗？

我不太清楚具体的问题，也许你可以从文件权限的思路出发，看一下是不是哪个文件没有写入的权限，导致最后设置保存失败。

**Comment by garrettzuo** [comment]
并没有，目前我准备晚上下班试试家里的网络看看
