### ISSUE TITLE
侧栏预约菜单中的子项目悬浮时能显示预约块完整内容

### ISSUE THREAD

**Issue by chenshinshi** [frostime/siyuan-dailynote-today#147]
![image](https://github.com/frostime/siyuan-dailynote-today/assets/125173405/f2aa301c-f777-4df2-a580-9ce364426922)
就像文档：
![image](https://github.com/frostime/siyuan-dailynote-today/assets/125173405/0975b50b-d763-487f-a08a-e8e63586a09d)
和大纲那样
![image](https://github.com/frostime/siyuan-dailynote-today/assets/125173405/6535efee-f1fa-4866-8236-391b5e08a63c)

**Comment by frostime** [comment]
悬浮显示内容应该可以，不过我觉得最好限制一下最大的字数。文档和大纲的字数都不太大，但是预约块可就不保证了。
