### ISSUE TITLE
解决预约块过大，导致预约窗口无法显示到确认按钮的问题

### ISSUE THREAD

**Issue by llh4github** [frostime/siyuan-dailynote-today#152]
使用版本：v1.2.2

预约块内有代码，内容有些长。弹出框无法滚动，所以点不到下面的确认按钮。

**Comment by frostime** [comment]
后面会想办法处理块过大的情况的。

现在作为权益之计，可以在设置当中关闭预约时候的弹出窗口。

![image](https://github.com/frostime/siyuan-dailynote-today/assets/27268127/7051f70d-0ad4-4442-91a6-1820537d48b9)
