### ISSUE TITLE
取消预约后，“查看预约”侧边栏信息残留

### ISSUE THREAD

**Issue by fenshen000** [frostime/siyuan-dailynote-today#159]
生成预约后，若将预约块取消，`查看预约`侧边栏仍存有被取消预约块的预约时间，并且无法手动删除，如下图所示，看起来就很累赘
![image](https://github.com/frostime/siyuan-dailynote-today/assets/43239563/8dd64955-b122-4203-9192-b8f1dd40171f)
大佬能否修改一下插件，取消预约块后，若对应预约时间无预约块，则在`查看预约`侧边栏自动删除该预约时间
感谢~

**Comment by fenshen000** [comment]
另外在README.md帮助文档中，SQL搜索语句中加入`group by B.created,B.content`，从而按照`创建时间`和`预约内容`合并重复查询结果，是否会更好一些呢
> 有时候不小心多次预约、删除和预约相同内容信息后，搜索结果可能会出现重复
> 来自SQL小白的一点建议

**Comment by frostime** [comment]
> group by B.created

思源 SQL 查询 block 的话好像没法使用分组查询吧。加了 group 以后，就只能展示 aggregate functions 的结果了，没什么意义啊。
