### ISSUE TITLE
增加配置按周展示笔记

### ISSUE THREAD

**Issue by windeye1000** [frostime/siyuan-dailynote-today#160]
现在月下面直接是按天展示的子笔记；
能否增加配置，可设置为按周展示子笔记。

**Comment by frostime** [comment]
抱歉我没有太理解你的意思，什么叫「按周展示子笔记」。
包括你说的「现在月下面直接是按天展示」我也没有搞明白你说的对应的是插件的哪个功能。
可否描述得详细一点，最好配上截图。

**Comment by frostime** [comment]
需求不明确，暂时先关闭了。
