### ISSUE TITLE
自动创建今日笔记能支持模板吗

### ISSUE THREAD

**Issue by SuperNoobTao** [frostime/siyuan-dailynote-today#165]
比如自动创建的今日笔记保持固定的格式这样子

## 明日待办

**Comment by frostime** [comment]
可以直接在笔记本页面里面指定模板，这是思源自带的功能。
点击笔记本的设置，在最下方可以设置模板

![image](https://github.com/frostime/siyuan-dailynote-today/assets/27268127/80d35db4-faa9-4c85-8370-718f1e02b329)

**Comment by frostime** [comment]
![image](https://github.com/frostime/siyuan-dailynote-today/assets/27268127/1d72f39a-27ef-437a-bc19-8faf886c87d4)

**Comment by SuperNoobTao** [comment]
好的谢谢！搞定了~
