### ISSUE TITLE
类 logseq 的日记文档流

### ISSUE THREAD

**Issue by frostime** [frostime/siyuan-dailynote-today#168]

**Comment by OriOYue** [comment]
这个功能很nice，不知道什么时候能用上，期待。

**Comment by frostime** [comment]
> 这个功能很nice，不知道什么时候能用上，期待。

现在用文档流插件也能展示日记流，就是要自己写 SQL。
https://ld246.com/article/1701761466782/comment/1702030656078#comments

后面应该是会基于文档流插件打一些配合，来实现这个功能。

**Comment by OriOYue** [comment]
好的，感谢。

**Comment by frostime** [comment]
文档流中实现了日记规则。

后续需要自动打开流式日记的话，就直接调用文档流插件功能，不在本插件中重复实现。
