### ISSUE TITLE
多窗口模式下，使用顶栏菜单打开日记的行为，会错误的广播到所有窗口中

### ISSUE THREAD

**Issue by Jiangshuon** [frostime/siyuan-dailynote-today#171]
大佬，希望优化下，蛮影响使用的

**Comment by frostime** [comment]
额，首先我不太理解什么叫「打开多个pdf窗口的情况下」「pdf窗口都会切换到日记页面」

我自己简单测试了一下，双栏打开两个 PDF。

![image](https://github.com/frostime/siyuan-dailynote-today/assets/27268127/8a27ab36-8fa8-4724-bc71-9afe48004fd8)

然后点击插件创建日记，正在激活中的那一边的文档切换到了日记页面中。

![image](https://github.com/frostime/siyuan-dailynote-today/assets/27268127/8ab7b243-814f-46ef-836a-0f6fe94aa3c8)

这个逻辑好像没什么问题啊？请问你值得希望优化的地方在哪？

**Comment by Jiangshuon** [comment]
不是的，我截下图，大佬你再试下

1、目前打开三个窗口，第一个窗口是文档页面，另外两个是pdf窗口

<img width="583" alt="2288aa55c638387dc6ec0400f47f9eb" src="https://github.com/frostime/siyuan-dailynote-today/assets/67137548/ca4dd8dd-4daa-495f-b2a1-3cfdd2cec9da">

2、进入第一个窗口，点击今日笔记创建新日记

3、三个窗口均切换成了日记页面（按理说另外两个不应该切换）

![71a21c7d44a3a189983c60ca4b086cc](https://github.com/frostime/siyuan-dailynote-today/assets/67137548/fe9e4cbb-3387-4c6b-8e23-c44fe645179c)

**Comment by frostime** [comment]
是像这样的三个独立的窗口是吗？
![image](https://github.com/frostime/siyuan-dailynote-today/assets/27268127/fd91795b-07dd-46b0-a594-4b9c8930a570)

**Comment by Jiangshuon** [comment]
是的，不是用双栏打开的，是独立的三个窗口
