### ISSUE TITLE
还存在广播到多窗口的问题

### ISSUE THREAD

**Issue by Jiangshuon** [frostime/siyuan-dailynote-today#174]
大佬，今日笔记的广播到多窗口还存在问题，多窗口下，新建第一个日记没问题，然后紧接着再新建一个日记（其他笔记本的），又会广播到其他所有窗口

**Comment by frostime** [comment]
我重新试了一下，发现这个是内核的问题。

内核当中，如果你新建了一个日记，那么这个事件就是会自动广播到全体窗口中。

![image](https://github.com/frostime/siyuan-dailynote-today/assets/27268127/fefb980f-22c7-4165-8d15-731751fb9f2b)

所以具体到插件的表现就是，如果你打开的是一个已经创建的日记有「√」符号，那么就不会广播到其他窗口；但是如果你打开的是一个不存在的日记，那么新建并打开这个日记的行为就是会广播到别的窗口。

总结就是：没招，内核写死了。除非我不用内核的 API，而是自己实现创建日记的功能——但是内核API自动实现了读入日记模板的功能，如果不用API需要自己手动处理，会很麻烦，所以我的建议是忍忍算了。

**Comment by Jiangshuon** [comment]
对了大佬，我直接按Alt+5，确实会广播。那这样算是思源内核的bug吧？应该给D大提issue吗

**Comment by frostime** [comment]
> 对了大佬，我直接按Alt+5，确实会广播。那这样算是思源内核的bug吧？应该给D大提issue吗

不算 bug，看代码是设计如此，但是我觉得可以提一下看看能不能改掉。这个广播行为感觉没杀必要性。

**Comment by frostime** [comment]
我先关了，有事情就在这下面说。

**Comment by Jiangshuon** [comment]
好的，那我去提下
