### ISSUE TITLE
能否支持查询和删除所有空内容的日记？

### ISSUE THREAD

**Issue by OriOYue** [frostime/siyuan-dailynote-today#178]
作者大大，能否支持查询和删除所有空内容的日记？因为，有时候可能打开了日记，但是又暂时没有内容可写，最后又忘记删除，导致这种空笔记越来越多
所以希望能像logseq那样，删除空日记。
![image](https://github.com/frostime/siyuan-dailynote-today/assets/72482686/bbe8544d-518d-4d8c-a376-720422dd16e4)

**Comment by frostime** [comment]
这个可以用 quicker 动作来做，有一个现成的工具可以自动检测所有空文档然后删除。

https://getquicker.net/Sharedaction?code=a65cd9c1-42fc-43fd-44d4-08dba7ba3b5d

**Comment by frostime** [comment]
思源里面日记就是普通的文档，而不同的人可能设置的日记路径模板不一样，搜索起来起始挺麻烦的。
所以「查找空的日记」这个功能实现起来可能还不如直接实现「查找空的文档」来的简单。

**Comment by frostime** [comment]
先关了，还有问题可以继续在这个 issue 下提
