### ISSUE TITLE
移动端点击按钮会闪烁一下

### ISSUE THREAD

**Issue by Jiangshuon** [frostime/siyuan-dailynote-today#185]
有个小问题，点击《今日笔记》，会闪烁抖动一下才会进入日记选择页面

**Comment by frostime** [comment]
我这边移动端无法复现出你说的「闪烁一下」，可能是设备差异的问题？

**Comment by Jiangshuon** [comment]
大佬，我是红米K40，附件是闪烁录屏，您没有吗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月19日(周二) 中午11:11
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [frostime/siyuan-dailynote-today] 移动端点击按钮会闪烁一下 (Issue #185)




 
我这边移动端无法复现出你说的「闪烁一下」，可能是设备差异的问题？

**Comment by frostime** [comment]
我这边是华为系列的，可能是由于机型适配之类的问题吧。
我用的都是思源提供的插件 API，应该没有特别加别的东西。

你在移动端用别的插件也会有闪烁问题吗？

另外确认一下，你说的点击闪烁是指点击菜单栏按钮是吧？

![image](https://github.com/frostime/siyuan-dailynote-today/assets/27268127/316d98d9-71bc-4759-a67a-1fc8a99ead53)

**Comment by Jiangshuon** [comment]
哦哦，用其他插件也是这样，那没事了，适配问题，多谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月19日(周二) 中午1:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [frostime/siyuan-dailynote-today] 移动端点击按钮会闪烁一下 (Issue #185)




 
我这边是华为系列的，可能是由于机型适配之类的问题吧。
 我用的都是思源提供的插件 API，应该没有特别加别的东西。
 
你在移动端用别的插件也会有闪烁问题吗？
 
另外确认一下，你说的点击闪烁是指点击菜单栏按钮是吧？
 
image.png (view on web)
