### ISSUE TITLE
允许不选择开始时间和截止时间

### ISSUE THREAD

**Issue by 7sevenseven** [frostime/siyuan-dailynote-today#187]

**Comment by frostime** [comment]
您好，请问你指的是哪个功能的「开始和截止时间」？

**Comment by frostime** [comment]
您好，由于您这个 issue 描述不太清楚，我也不明白你要的是什么，所以暂时先关闭。

如果你还有什么意见或者要补充的可以在这个 issue 下回复；如果合理，这个 issue 也可以被重新开启。
