### ISSUE TITLE
提一个小问题

### ISSUE THREAD

**Issue by WolkeAtreide** [frostime/siyuan-dailynote-today#19]
我记得原先用的时候，勾选几个开机的时候就能自动新建几个文档。现在只能弹出第一个？感觉还是原来的好用
![image](https://user-images.githubusercontent.com/101959415/236742312-24c347aa-8cc4-46f7-b668-d2824de03bfa.png)

**Comment by WolkeAtreide** [comment]
现在好了，原因未知，提一个新问题，如何取消勾选呢？因为工作问题，每隔一段时间都会换一个文件夹。

**Comment by frostime** [comment]
不好意思，我没有太理解你的意思。

1. 下拉框里面的「√」符号是表示「对应的笔记本里已经创建了今天的日记」的意思；这个是插件自己生成的一个标识符。如果你把对应的日记删掉了，那下拉框会自动更新把「√」符号去掉（删掉后，再次打开下拉框就会发现「√」已经没了）。
2. 「勾选几个开机的时候就能自动新建几个文档。现在只能弹出第一个」——这句话我没有看明白，这个插件一直都是只会自动在第一个笔记本中创建今天的日记。我的说明文档里面也提到过如何更改默认的笔记本，不过那个操作确实很繁琐，我后面会出一个设置选项，可以自行指定默认的笔记本。
3. 至于「自动新建几个文档」，如果你的意思是启动插件的时候可以自动创建多个日记，那这个功能我可以考虑在后面加入。
4. **但是**：由于这几个版本官方要把插件系统整合到本体，这段时间内社区插件的作者也不建议我们更新插件。所以在整合完成前，本插件不会有功能上的更新，需要等待一段时间。

**Comment by frostime** [comment]
另外提一下，官方插件整合了以后，有可能顶端工具栏就不允许放下拉框了😢……我做了一个菜单图标作为替代，在现在最新的 v0.7.0 有这个切换选项，你可以先习惯一下。

![image](https://user-images.githubusercontent.com/27268127/236745275-ea243922-b3ef-423a-a806-7b3c50a2331f.png)

**Comment by WolkeAtreide** [comment]
懂你的意思了。
不过我在实际使用过程中，存在同时打开两个笔记的现象。就是1和2的dailynote在开软件的时候同时开启。
如图所示，两个同时打开了
![image](https://user-images.githubusercontent.com/101959415/236791130-42ed1044-802a-4510-a241-29341a8e01b9.png)
不过这种现象不稳定，时有时无，所以我才会来问一下。

**Comment by WolkeAtreide** [comment]
> 另外提一下，官方插件整合了以后，有可能顶端工具栏就不允许放下拉框了😢……我做了一个菜单图标作为替代，在现在最新的 v0.7.0 有这个切换选项，你可以先习惯一下。
> 
> ![image](https://user-images.githubusercontent.com/27268127/236745275-ea243922-b3ef-423a-a806-7b3c50a2331f.png)

这个其实比下拉菜单好看些。。。

**Comment by frostime** [comment]
> > 另外提一下，官方插件整合了以后，有可能顶端工具栏就不允许放下拉框了😢……我做了一个菜单图标作为替代，在现在最新的 v0.7.0 有这个切换选项，你可以先习惯一下。
> > ![image](https://user-images.githubusercontent.com/27268127/236745275-ea243922-b3ef-423a-a806-7b3c50a2331f.png)
> 
> 这个其实比下拉菜单好看些。。。

其实我更喜欢下拉框，占得面积大容易点到……不过确实美观度上弱一点。

**Comment by frostime** [comment]
我后面会加入手动指定默认笔记本的选项的。至于那个 bug 我似乎也没遇到过，只能说有待观察吧。
如果没有别的事情，我先把这个 issue 关了。

**Comment by WolkeAtreide** [comment]
> 我后面会加入手动指定默认笔记本的选项的。至于那个 bug 我似乎也没遇到过，只能说有待观察吧。 如果没有别的事情，我先把这个 issue 关了。

有点难过的是，这居然是个bug。。希望以后能加上这个bug
