### ISSUE TITLE
为过去的 Daily Note 补充文档属性 | 处理文档数量为 0 的异常情况

### ISSUE THREAD

**Issue by Foundation-Maker** [frostime/siyuan-dailynote-today#191]
![CleanShot_2024-04-26 _ 17 30 15@2x](https://github.com/frostime/siyuan-dailynote-today/assets/46839690/58717991-66cd-44e1-9016-bc0f6b4ea2a6)

就一直停顿在这个状态。

**Comment by frostime** [comment]
控制台有无特别的输出？比如什么警告或者报错之类的？

**Comment by Foundation-Maker** [comment]
![CleanShot_2024-04-26 _ 19 09 25@2x](https://github.com/frostime/siyuan-dailynote-today/assets/46839690/4037e16d-6d84-4b10-80fe-166ba8bdbb12)

**Comment by Foundation-Maker** [comment]
> ![CleanShot_2024-04-26 _ 19 09 25@2x](https://private-user-images.githubusercontent.com/46839690/325956939-4037e16d-6d84-4b10-80fe-166ba8bdbb12.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMzAwOTMsIm5iZiI6MTcxNDEyOTc5MywicGF0aCI6Ii80NjgzOTY5MC8zMjU5NTY5MzktNDAzN2UxNmQtNmQ4NC00YjEwLTgwZmUtMTY2YmE4YmRiYjEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDExMDk1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyOWM2MzkzMmNmMDc5ZDhhYTAxM2VhOGU3ZjQxMmRjMGUyMmZkMjIwYzFkNTEwMzYxMjAzOTk5YTIxOGZjNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wj5tMUchbGaVTW-HAG0KYAa9lq_ZD3VfpuZBF7xptBw)

![CleanShot_2024-04-26 _ 19 10 08@2x](https://github.com/frostime/siyuan-dailynote-today/assets/46839690/735bffbb-d1e4-4812-8f5e-9c7ebc29f57e)

**Comment by frostime** [comment]
请问你在控制台中有没有看到这个警告？

![image](https://github.com/frostime/siyuan-dailynote-today/assets/27268127/4315cd52-ef3e-41be-bb0c-a38666027a4c)

**Comment by Foundation-Maker** [comment]
> 请问你在控制台中有没有看到这个警告？
> 
> ![image](https://private-user-images.githubusercontent.com/27268127/325962275-4315cd52-ef3e-41be-bb0c-a38666027a4c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMzE1NDIsIm5iZiI6MTcxNDEzMTI0MiwicGF0aCI6Ii8yNzI2ODEyNy8zMjU5NjIyNzUtNDMxNWNkNTItZWYzZS00MWJlLWJiMGMtYTM4NjY2MDI3YTRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDExMzQwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0MjU3NTQ0ZjRjYmZiOWY4MWY2YTQyMGQ1NDU3MjVhMDBjMDQ2NGY2NTg5OGJmOTQzNjRjNDgzNjQ0NjNlZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wHspuPC56BqAvx3A44y_tDH8P5MxQEGtshJEMeUkXF4)

有的。 
![CleanShot_2024-04-26 _ 19 36 32@2x](https://github.com/frostime/siyuan-dailynote-today/assets/46839690/f7faa674-73b2-4b98-a070-06eae29f3fe2)
但是我同时设置了 ，但是他找的确实另一个文件夹
![CleanShot_2024-04-26 _ 19 36 48@2x](https://github.com/frostime/siyuan-dailynote-today/assets/46839690/e400e41b-d76b-42ca-bf94-c8cea83c4ef5)

**Comment by frostime** [comment]
「000-工作台」的日记路径配置是什么？

**Comment by Foundation-Maker** [comment]
> 「000-工作台」的日记路径配置是什么？

原先日记在 工作台这个 ID 20240307203354-ux9pzab
路径：/daily note/{{now | date "2006/01"}}/{{now | date "2006-01-02"}}

但是日记现在不在这里。在 20231209210018-omfanuo
路径为：/dailynote/{{now | date "2006/2006-01"}}/{{now | date "2006-01-02"}}-周{{now | WeekdayCN}}

**Comment by frostime** [comment]
> > 「000-工作台」的日记路径配置是什么？
> 
> 原先日记在 工作台这个 ID 20240307203354-ux9pzab 路径：/daily note/{{now | date "2006/01"}}/{{now | date "2006-01-02"}}
> 
> 但是日记现在不在这里。在 20231209210018-omfanuo 路径为：/dailynote/{{now | date "2006/2006-01"}}/{{now | date "2006-01-02"}}-周{{now | WeekdayCN}}

1. 问：那么目前「000-工作台」笔记本下面还有日记文档吗？还是都移动到新的笔记本里面了？
2. 你尝试关闭「000-工作台」笔记本，然后更新一下状态。然后再运行一次看看是否还会报错？

![image](https://github.com/frostime/siyuan-dailynote-today/assets/27268127/69af26f4-6ef9-459f-80aa-49c113ac3a97)

![image](https://github.com/frostime/siyuan-dailynote-today/assets/27268127/07f66524-57b0-4c76-a0d1-8742c965e69d)

**Comment by frostime** [comment]
> 1、已经没有文档了。 都已经移动到新的中了。 2、关闭生效了。但是有问题。 2.1、出现了寻找其他文件夹 ![CleanShot_2024-04-26 _ 20 12 21@2x](https://private-user-images.githubusercontent.com/46839690/325971856-486f51a3-24ef-4c32-92ce-9bf80a2fe32f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMzQyNDMsIm5iZiI6MTcxNDEzMzk0MywicGF0aCI6Ii80NjgzOTY5MC8zMjU5NzE4NTYtNDg2ZjUxYTMtMjRlZi00YzMyLTkyY2UtOWJmODBhMmZlMzJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDEyMTkwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjNzkxZGY2MGM1ZWRlMzU0Nzg5N2ViMDQwOGEwNGViOWUzMTQwOGMwMjNiOTIyZDQ5MjQwNjE5NTMzNmMzMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IhNUotts7U7s07y6bdvOtpPo-KF5pdSXmRzV9SmQV4Y) 2.2、只匹配了部分的文档。比如我这里只匹配了从 2022-12-12 日之后的日记。

1. 引发一开始你提出的运行失败的问题的原因应该是我代码里没有做好「没有日记文档」的异常情况处理
2. 「寻找其他文件夹」这个我每搞明白是怎么回事，先放着
3. 「只匹配了部分的文档」大概率原因是那些没有被匹配的文档创建日记比时间日期要晚；插件会首先匹配最早创建的文档当作最早的日记，而如果你在后面补创建了更早之前的日记，就无法被正常匹配到
    - 关于这个问题，请关注 #182 这个 issue，后面会优化的

**Comment by Foundation-Maker** [comment]
> > 1、已经没有文档了。 都已经移动到新的中了。 2、关闭生效了。但是有问题。 2.1、出现了寻找其他文件夹 ![CleanShot_2024-04-26 _ 20 12 21@2x](https://private-user-images.githubusercontent.com/46839690/325971856-486f51a3-24ef-4c32-92ce-9bf80a2fe32f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMzQyNDMsIm5iZiI6MTcxNDEzMzk0MywicGF0aCI6Ii80NjgzOTY5MC8zMjU5NzE4NTYtNDg2ZjUxYTMtMjRlZi00YzMyLTkyY2UtOWJmODBhMmZlMzJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDEyMTkwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjNzkxZGY2MGM1ZWRlMzU0Nzg5N2ViMDQwOGEwNGViOWUzMTQwOGMwMjNiOTIyZDQ5MjQwNjE5NTMzNmMzMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IhNUotts7U7s07y6bdvOtpPo-KF5pdSXmRzV9SmQV4Y) 2.2、只匹配了部分的文档。比如我这里只匹配了从 2022-12-12 日之后的日记。
> 
> 1. 引发一开始你提出的运行失败的问题的原因应该是我代码里没有做好「没有日记文档」的异常情况处理
> 2. 「寻找其他文件夹」这个我每搞明白是怎么回事，先放着
> 3. 「只匹配了部分的文档」大概率原因是那些没有被匹配的文档创建日记比时间日期要晚；插件会首先匹配最早创建的文档当作最早的日记，而如果你在后面补创建了更早之前的日记，就无法被正常匹配到
>    
>    * 关于这个问题，请关注 [迁移日记属性的时候，手动指定开始日期 #182](https://github.com/frostime/siyuan-dailynote-today/issues/182) 这个 issue，后面会优化的

好的。针对第三条，是以前的同步 BUG导致，移动到新的文件夹时，创建了新文档。
我手动修复，把最早的日记，时间给改一下吧。 这样做能行吧。

**Comment by frostime** [comment]
> > > 1、已经没有文档了。 都已经移动到新的中了。 2、关闭生效了。但是有问题。 2.1、出现了寻找其他文件夹 ![CleanShot_2024-04-26 _ 20 12 21@2x](https://private-user-images.githubusercontent.com/46839690/325971856-486f51a3-24ef-4c32-92ce-9bf80a2fe32f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMzQyNDMsIm5iZiI6MTcxNDEzMzk0MywicGF0aCI6Ii80NjgzOTY5MC8zMjU5NzE4NTYtNDg2ZjUxYTMtMjRlZi00YzMyLTkyY2UtOWJmODBhMmZlMzJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDEyMTkwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjNzkxZGY2MGM1ZWRlMzU0Nzg5N2ViMDQwOGEwNGViOWUzMTQwOGMwMjNiOTIyZDQ5MjQwNjE5NTMzNmMzMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IhNUotts7U7s07y6bdvOtpPo-KF5pdSXmRzV9SmQV4Y) 2.2、只匹配了部分的文档。比如我这里只匹配了从 2022-12-12 日之后的日记。
> > 
> > 
> > 
> > 1. 引发一开始你提出的运行失败的问题的原因应该是我代码里没有做好「没有日记文档」的异常情况处理
> > 2. 「寻找其他文件夹」这个我每搞明白是怎么回事，先放着
> > 3. 「只匹配了部分的文档」大概率原因是那些没有被匹配的文档创建日记比时间日期要晚；插件会首先匹配最早创建的文档当作最早的日记，而如果你在后面补创建了更早之前的日记，就无法被正常匹配到
> >    
> >    * 关于这个问题，请关注 [迁移日记属性的时候，手动指定开始日期 #182](https://github.com/frostime/siyuan-dailynote-today/issues/182) 这个 issue，后面会优化的
> 
> 好的。针对第三条，是以前的同步 BUG导致，移动到新的文件夹时，创建了新文档。 我手动修复，把最早的日记，时间给改一下吧。 这样做能行吧。

文档创建时间正常手段好像改不了，你最简单的方法是拖一个更早一点的文档到你的日记目录下，这样插件就会把「最早的时间」判定的更加早。


或者如果你有自信，可以直接改原始的 sy 文件里面的创建时间字段。

**Comment by Foundation-Maker** [comment]
嗯嗯，这个没事，时间我自己改过

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年04月26日 下午8:31 |
| 收件人 | frostime/siyuan-dailynote-today ***@***.***> |
| 抄送人 | Foundation ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [frostime/siyuan-dailynote-today] 为过去的 Daily Note 补充文档属性 | 处理文档数量为 0 的异常情况 (Issue #191) |

1、已经没有文档了。 都已经移动到新的中了。 2、关闭生效了。但是有问题。 2.1、出现了寻找其他文件夹 2.2、只匹配了部分的文档。比如我这里只匹配了从 2022-12-12 日之后的日记。

引发一开始你提出的运行失败的问题的原因应该是我代码里没有做好「没有日记文档」的异常情况处理

「寻找其他文件夹」这个我每搞明白是怎么回事，先放着

「只匹配了部分的文档」大概率原因是那些没有被匹配的文档创建日记比时间日期要晚；插件会首先匹配最早创建的文档当作最早的日记，而如果你在后面补创建了更早之前的日记，就无法被正常匹配到

关于这个问题，请关注 迁移日记属性的时候，手动指定开始日期 #182 这个 issue，后面会优化的

好的。针对第三条，是以前的同步 BUG导致，移动到新的文件夹时，创建了新文档。 我手动修复，把最早的日记，时间给改一下吧。 这样做能行吧。

文档创建时间正常手段好像改不了，你最简单的方法是拖一个更早一点的文档到你的日记目录下，这样插件就会把「最早的时间」判定的更加早。

或者如果你有自信，可以直接改原始的 sy 文件里面的创建时间字段。
