### ISSUE TITLE
需求：设置默认日志模板

### ISSUE THREAD

**Issue by rgzntrade** [frostime/siyuan-dailynote-today#194]
创建日志文件的同时将默认日志模板的内容也输入到日志中。

**Comment by frostime** [comment]
这个在思源里面就能设置啊。打开笔记本设置，然后填写模板路径。
![image](https://github.com/frostime/siyuan-dailynote-today/assets/27268127/cf93011f-fec2-46dd-b7c7-4743ef568af7)
