### ISSUE TITLE
二次打开后输入光标缺失。

### ISSUE THREAD

**Issue by lpanlab** [frostime/siyuan-dailynote-today#200]
win11，当日首次打开时正常，二次及以后打开会提示打开当日日记，如图
![image](https://github.com/user-attachments/assets/86af997f-62c8-42eb-becf-96203fd19dcf)
不管是点击ok还是X后进入，点击文本无法出现输入光标，且输入后如图所示，无法在正文输入，切换中英文输入法都是一样的。
![image](https://github.com/user-attachments/assets/8f341d4c-1920-4d6a-9c6d-d22fbf515fca)

**Comment by frostime** [comment]
「二次及以后打开」是指什么？关闭思源再打开？可否提供更加详细的复现方案。

**Comment by frostime** [comment]
我尝试多次重启思源，并没用遇到你说的这种情况。😥

**Comment by lpanlab** [comment]
> 「二次及以后打开」是指什么？关闭思源再打开？可否提供更加详细的复现方案。

是的，指当日第一次打开思源后关闭再打开，我录了一下屏幕，在后面链接可以请你看一下。我觉得可能是跟打开当日日记有关系，因为后面可以看到，打开后并没有回到当日日记。
https://www.jianguoyun.com/p/DS5_aqYQ6NKPBhjWlNcFIAA。

**Comment by frostime** [comment]
我又尝试重复了几遍还是没有复现出来。你能否启动的时候把控制台打开，看看有没有什么报错？

![image](https://github.com/user-attachments/assets/a0fa9aa9-bb37-4fd5-90fa-e5497e8959c8)

**Comment by lpanlab** [comment]
> 我又尝试重复了几遍还是没有复现出来。你能否启动的时候把控制台打开，看看有没有什么报错？
> 
> ![image](https://private-user-images.githubusercontent.com/27268127/367507456-a0fa9aa9-bb37-4fd5-90fa-e5497e8959c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2MjE0OTEsIm5iZiI6MTcyNjYyMTE5MSwicGF0aCI6Ii8yNzI2ODEyNy8zNjc1MDc0NTYtYTBmYTlhYTktYmIzNy00ZmQ1LTkwZmEtZTU0OTdlODk1OWM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE4VDAwNTk1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiODRjYzRjNzExM2Q3MGE1OTZkNmUyMGYzYWE0NzNiY2YzYThmN2M4MmU1MWIxZGJkZGQ0YmE5OTg5MjZmNTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6b2bQ1bRdb1UkL-72Ls5hmsSbLrfOKUZSGXpwvJ0dvQ)

你好，图一是错误
![image](https://github.com/user-attachments/assets/e2e2df8e-2e41-4d4c-8927-b31c76907d77)
图二是开启全局后，还是会与之前一样，只是控制台信息变了
![image](https://github.com/user-attachments/assets/3a5c68bd-2497-4648-b0c4-d9c4228177a1)

**Comment by frostime** [comment]
这个看着似乎不是插件的日志输出。
![image](https://github.com/user-attachments/assets/b82681cd-43f6-4f02-894e-e76778211b83)


你打开侧边栏看看插件本体日志有无报错？

![image](https://github.com/user-attachments/assets/e7d379e3-45c9-4c79-95d9-1557566a41a4)


----

另外请问一下，你这个问题是在上个版本更新之后才出现的吗？

**Comment by lpanlab** [comment]
插件没有报错，是main的报错。记不得是更新之前还是之后的了。
![image](https://github.com/user-attachments/assets/0ed6a22e-d5c6-4449-90cf-f7564cd60e91)

**Comment by frostime** [comment]
这个实在不太好排查。

或者你可以退版本试试。

方案是：

1. 手动在 release 里面下载 package.json，解压缩
2. 打开插件所在位置
![image](https://github.com/user-attachments/assets/868eedbc-60c5-45d4-8740-f7969f3d0db5)
3. 关闭插件，然后把 package.json 里面的东西覆盖进去
4. 重启插件

**Comment by lpanlab** [comment]
好的，谢谢，我试试，实在不行就这么用，也不是不能用，我这可能是个例。

**Comment by lpanlab** [comment]
今天思源更新以后恢复正常了。
