### ISSUE TITLE
样式建议：目前的层级列表可以削减成两级吗？

### ISSUE THREAD

**Issue by luluciamk** [frostime/siyuan-dailynote-today#202]
如图
![image](https://github.com/user-attachments/assets/65cc30c6-1ce7-44b4-ae47-4b56127f6e1c)
 这个层级列表有五级，**层层开启or折叠都实在太繁琐**，靠着另一个插件“日历面板”操作跳转或许很方便，可是后续来整理时，需要经常频繁打开子层文档。
目前的这个样式，每天的dailynote还没有新建子文档就有五级，一旦深入使用，很难不保证每天dailynote内部还有层级子文档，那么总体层级就可能达到7层+。这个嵌套度相当可怕，视觉上很累赘，操作上很繁琐。

我的建议是——可否将这个层级列表削减成两级？

原因是：
1. 每天新建的dailynote文档，其标题本来就是年-月-月标识，这种情况下，年-月-日的文件夹层级结构是否与文档信息产生重复？
2.  若说这种层级文件夹用于储存dailynote（即确定其唯一位置），这种设计的应用步骤，相较发生在产生文档前，还是应用于“整理文档时”更有必要。
翻译一下意思是，记录时要求的是文档查看的便捷，整理时要求的是文档查看的直接，唯有定期整理需要的是文档位置的唯一固定。
即，平时文档树都是直接铺展开来的dailynote，之后是否有这种年月日文件夹，可以按照使用者的需求来进行整理，而不是在记录前便强行固定其位置——这只造成了后续查看和管理的不便。

相较ob还需要在文件夹管理附件，思源连这点麻烦也省了，可是目前这个层级结构，实在不能称之为高效。
参考，类似ob的这种架构，不是更直观吗？如果后续使用者想要做年月日的架构，也可以自己选择生成文件夹来储存——而不是非得存在这个笔记本里啊（这种场景下，现在生成的年月日文件夹，在后续管理时反倒只会增加阻力和障碍，因为这种层级结构，先天将笔记内容给僵死固定在了深层文档里面。）
![image](https://github.com/user-attachments/assets/38a293dc-f217-4e1a-bd55-d42b9798d04f)

大大未来克以削减这个层级吗？
现在越来越多的实例证明，笔记不能完全纯粹依靠dailynote笔记流，这种方法可以无压记录，却不利于后期的管理，真就只能轻量按需使用，还是得和双链or文档树or数据库等联动使用。
如果再加上现在这个国度嵌套的层级文件夹，轻量管理都十分费劲，

我的想法——

第一层级就是插件所选择的“笔记本inbox（例）”。
第二层级就是inbox下的子文档——按日期生成。
之后如果使用者想整理，可以按照自己的需求，在inbox或者其他笔记本里自己选择性生成年月日结构，或者就直接把某些文档挪动到其他笔记本里（因为有时候某些内容完全不值得用一个page来记录。）
即，删掉目前的——
dailynote这一层
年这一层
月这一层
只保留“日”这一层。

如果是这种五级嵌套，光是看看都觉得压力山大。
每次都需要各种展开各种折叠，这无形中增加了多少步骤啊……
希望大大一定要认真对待一下这个问题，不过我不清楚，这个是能做到的吗？这种情况下，“今日笔记”就像一个便捷生成笔记的快捷操作。（当然其他功能我认为很不错））

**Comment by frostime** [comment]
你说的这个日记路径的配置，是在思源的设置里面更改的，和插件关系不大。

![image](https://github.com/user-attachments/assets/6d6919aa-1836-4ee0-a02c-b8588cf98392)

关于如如何更改，可以参考这篇文章：https://ld246.com/article/1715065433237#%E5%B8%B8%E7%94%A8%E7%9A%84%E6%97%B6%E9%97%B4%E5%87%BD%E6%95%B0
