### ISSUE TITLE
笔记本id错误，无法加入黑名单

### ISSUE THREAD

**Issue by KeeeevinK** [frostime/siyuan-dailynote-today#205]
1. 笔记本id识别有问题，我尝试用alt+f5替换会出现
![PixPin_2024-11-28_17-14-49](https://github.com/user-attachments/assets/fb5d43d1-d266-4eed-9373-8c19d83bdff0)

2. 无法加入黑名单，我的文件夹排第一是Inbox，每次都会在Inbox创建日记
![PixPin_2024-11-28_17-17-16](https://github.com/user-attachments/assets/f6590a0e-0d46-4b78-b1aa-d28922c397e1)
    - 打开前 
    ![PixPin_2024-11-28_17-18-06](https://github.com/user-attachments/assets/5cb20abc-34bf-44b6-92d2-31bd7c5c2db6)
    - 打开后
    ![PixPin_2024-11-28_17-19-01](https://github.com/user-attachments/assets/b8aee38f-4e3d-4d45-8b3a-e41f2e83a507)

**Comment by frostime** [comment]
这个配置了吗？
![image](https://github.com/user-attachments/assets/9384113f-05a7-4043-8e9a-b58ee2937519)

**Comment by KeeeevinK** [comment]
> 这个配置了吗？
> ![image](https://github.com/user-attachments/assets/9384113f-05a7-4043-8e9a-b58ee2937519)
> 

配置了![390717351-fb5d43d1-d266-4eed-9373-8c19d83bdff0~2.png](https://github.com/user-attachments/assets/60929477-076c-455e-9394-39ea7ccb6a7c)

**Comment by KeeeevinK** [comment]
> 这个配置了吗？
> ![image](https://github.com/user-attachments/assets/9384113f-05a7-4043-8e9a-b58ee2937519)
> 

配置了![390717351-fb5d43d1-d266-4eed-9373-8c19d83bdff0~2.png](https://github.com/user-attachments/assets/60929477-076c-455e-9394-39ea7ccb6a7c)

**Comment by frostime** [comment]
尝试：

1. 把黑名单清空一下
![image](https://github.com/user-attachments/assets/97787de9-a8e3-4d8c-ab09-561190af9705)


2. 更新一下全局状态
![image](https://github.com/user-attachments/assets/79d25d00-448c-47e7-8080-7f8b069943b3)

然后再试试看？

**Comment by KeeeevinK** [comment]
> 尝试：
> 
> 1. 把黑名单清空一下
>    ![image](https://private-user-images.githubusercontent.com/27268127/390810216-97787de9-a8e3-4d8c-ab09-561190af9705.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4MDM4NTksIm5iZiI6MTczMjgwMzU1OSwicGF0aCI6Ii8yNzI2ODEyNy8zOTA4MTAyMTYtOTc3ODdkZTktYThlMy00ZDhjLWFiMDktNTYxMTkwYWY5NzA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDE0MTkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwMDk0NWU0MGQ1NzQzMjRjZWY3M2RjN2RjNTcwOTczMmNkZjRiZGY5M2YyNWI0MjBmZTYwZGNkMmE4NTNlM2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PPisQ1rlVcD01axHmkQlaTXoeY3xvw6NadfMjRR7cm0)
> 2. 更新一下全局状态
>    ![image](https://private-user-images.githubusercontent.com/27268127/390810057-79d25d00-448c-47e7-8080-7f8b069943b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4MDM4NTksIm5iZiI6MTczMjgwMzU1OSwicGF0aCI6Ii8yNzI2ODEyNy8zOTA4MTAwNTctNzlkMjVkMDAtNDQ4Yy00N2U3LTgwODAtN2Y4YjA2OTk0M2IzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDE0MTkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliYjA0NmQ1MGFjYjBlNzZjZjQ1ZTBhNzZkNzFlYzNhYjkzMTE4MjdkNDAzOTEyOWZjNzg5YzYxMGI3MzQxMGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7txi-B4wnOc6TMPw3K8ZXhAtbxDPxKyFaCYz-DQdm18)
> 
> 然后再试试看？

试了还是不行，会自动清空笔记本id，感觉像是不认这个id，覆写alt+5时直接提示不正确
我录了一段操作视频
![PixPin_2024-11-28_22-17-21](https://github.com/user-attachments/assets/a20dde46-de96-4aac-bba6-73f120694c27)

**Comment by frostime** [comment]
你搞错了，不是复制 daily note 文档的 ID。

![image](https://github.com/user-attachments/assets/5a152f01-b79a-42a8-b6ec-1c19402269c6)

是复制笔记本的 ID

![image](https://github.com/user-attachments/assets/a167e028-5eb6-4926-ba9f-04a29889edad)

**Comment by frostime** [comment]
> 好的谢谢🙏🥰，终于是解决这个老乱创建了，它这个ID也藏的太深了，一开始没找到就以为只有文档的ID了@frostime 不过自动打开好像还是没有生效？ ![PixPin_2024-11-28_23-52-03](https://private-user-images.githubusercontent.com/187881272/390847002-6a182cd1-ca29-43ef-bd6a-f438b2602d19.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4MTAwNDcsIm5iZiI6MTczMjgwOTc0NywicGF0aCI6Ii8xODc4ODEyNzIvMzkwODQ3MDAyLTZhMTgyY2QxLWNhMjktNDNlZi1iZDZhLWY0MzhiMjYwMmQxOS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOFQxNjAyMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMmYyOGM2YmVmM2ZlZmRkYmYxMWY5OWE1OGMwYjE0ZmZmYTY2ODk4ZmQ3ZTcyYTFlOTllY2IxMDc1MjE4NTZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.5kdXv7Qu6BdqDL1Y-Nsoo4oFMzA37jm4OEoKht80I8Q) [ ![PixPin_2024-11-28_23-52-03](https://private-user-images.githubusercontent.com/187881272/390847002-6a182cd1-ca29-43ef-bd6a-f438b2602d19.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4MTAwNDcsIm5iZiI6MTczMjgwOTc0NywicGF0aCI6Ii8xODc4ODEyNzIvMzkwODQ3MDAyLTZhMTgyY2QxLWNhMjktNDNlZi1iZDZhLWY0MzhiMjYwMmQxOS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOFQxNjAyMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMmYyOGM2YmVmM2ZlZmRkYmYxMWY5OWE1OGMwYjE0ZmZmYTY2ODk4ZmQ3ZTcyYTFlOTllY2IxMDc1MjE4NTZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.5kdXv7Qu6BdqDL1Y-Nsoo4oFMzA37jm4OEoKht80I8Q) ](https://private-user-images.githubusercontent.com/187881272/390847002-6a182cd1-ca29-43ef-bd6a-f438b2602d19.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4MTAwNDcsIm5iZiI6MTczMjgwOTc0NywicGF0aCI6Ii8xODc4ODEyNzIvMzkwODQ3MDAyLTZhMTgyY2QxLWNhMjktNDNlZi1iZDZhLWY0MzhiMjYwMmQxOS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOFQxNjAyMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMmYyOGM2YmVmM2ZlZmRkYmYxMWY5OWE1OGMwYjE0ZmZmYTY2ODk4ZmQ3ZTcyYTFlOTllY2IxMDc1MjE4NTZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.5kdXv7Qu6BdqDL1Y-Nsoo4oFMzA37jm4OEoKht80I8Q) [ ](https://private-user-images.githubusercontent.com/187881272/390847002-6a182cd1-ca29-43ef-bd6a-f438b2602d19.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4MTAwNDcsIm5iZiI6MTczMjgwOTc0NywicGF0aCI6Ii8xODc4ODEyNzIvMzkwODQ3MDAyLTZhMTgyY2QxLWNhMjktNDNlZi1iZDZhLWY0MzhiMjYwMmQxOS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOFQxNjAyMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMmYyOGM2YmVmM2ZlZmRkYmYxMWY5OWE1OGMwYjE0ZmZmYTY2ODk4ZmQ3ZTcyYTFlOTllY2IxMDc1MjE4NTZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.5kdXv7Qu6BdqDL1Y-Nsoo4oFMzA37jm4OEoKht80I8Q)

没有自动打开吗？你开一下开发者模式，看看控制台有没有什么报错之类的信息？

**Comment by KeeeevinK** [comment]
> > 好的谢谢🙏🥰，终于是解决这个老乱创建了，它这个ID也藏的太深了，一开始没找到就以为只有文档的ID了@frostime 不过自动打开好像还是没有生效？ ![PixPin_2024-11-28_23-52-03](https://private-user-images.githubusercontent.com/187881272/390847002-6a182cd1-ca29-43ef-bd6a-f438b2602d19.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4MTAwNDcsIm5iZiI6MTczMjgwOTc0NywicGF0aCI6Ii8xODc4ODEyNzIvMzkwODQ3MDAyLTZhMTgyY2QxLWNhMjktNDNlZi1iZDZhLWY0MzhiMjYwMmQxOS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOFQxNjAyMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMmYyOGM2YmVmM2ZlZmRkYmYxMWY5OWE1OGMwYjE0ZmZmYTY2ODk4ZmQ3ZTcyYTFlOTllY2IxMDc1MjE4NTZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.5kdXv7Qu6BdqDL1Y-Nsoo4oFMzA37jm4OEoKht80I8Q)
> >       
> >         [
> >           
> >             ![PixPin_2024-11-28_23-52-03](https://private-user-images.githubusercontent.com/187881272/390847002-6a182cd1-ca29-43ef-bd6a-f438b2602d19.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4MTAwNDcsIm5iZiI6MTczMjgwOTc0NywicGF0aCI6Ii8xODc4ODEyNzIvMzkwODQ3MDAyLTZhMTgyY2QxLWNhMjktNDNlZi1iZDZhLWY0MzhiMjYwMmQxOS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOFQxNjAyMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMmYyOGM2YmVmM2ZlZmRkYmYxMWY5OWE1OGMwYjE0ZmZmYTY2ODk4ZmQ3ZTcyYTFlOTllY2IxMDc1MjE4NTZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.5kdXv7Qu6BdqDL1Y-Nsoo4oFMzA37jm4OEoKht80I8Q)
> >           
> >         ](https://private-user-images.githubusercontent.com/187881272/390847002-6a182cd1-ca29-43ef-bd6a-f438b2602d19.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4MTAwNDcsIm5iZiI6MTczMjgwOTc0NywicGF0aCI6Ii8xODc4ODEyNzIvMzkwODQ3MDAyLTZhMTgyY2QxLWNhMjktNDNlZi1iZDZhLWY0MzhiMjYwMmQxOS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOFQxNjAyMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMmYyOGM2YmVmM2ZlZmRkYmYxMWY5OWE1OGMwYjE0ZmZmYTY2ODk4ZmQ3ZTcyYTFlOTllY2IxMDc1MjE4NTZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.5kdXv7Qu6BdqDL1Y-Nsoo4oFMzA37jm4OEoKht80I8Q)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://private-user-images.githubusercontent.com/187881272/390847002-6a182cd1-ca29-43ef-bd6a-f438b2602d19.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4MTAwNDcsIm5iZiI6MTczMjgwOTc0NywicGF0aCI6Ii8xODc4ODEyNzIvMzkwODQ3MDAyLTZhMTgyY2QxLWNhMjktNDNlZi1iZDZhLWY0MzhiMjYwMmQxOS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOFQxNjAyMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMmYyOGM2YmVmM2ZlZmRkYmYxMWY5OWE1OGMwYjE0ZmZmYTY2ODk4ZmQ3ZTcyYTFlOTllY2IxMDc1MjE4NTZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.5kdXv7Qu6BdqDL1Y-Nsoo4oFMzA37jm4OEoKht80I8Q)
> >         
> >        [ ![PixPin_2024-11-28_23-52-03](https://private-user-images.githubusercontent.com/187881272/390847002-6a182cd1-ca29-43ef-bd6a-f438b2602d19.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4MTAwNDcsIm5iZiI6MTczMjgwOTc0NywicGF0aCI6Ii8xODc4ODEyNzIvMzkwODQ3MDAyLTZhMTgyY2QxLWNhMjktNDNlZi1iZDZhLWY0MzhiMjYwMmQxOS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOFQxNjAyMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMmYyOGM2YmVmM2ZlZmRkYmYxMWY5OWE1OGMwYjE0ZmZmYTY2ODk4ZmQ3ZTcyYTFlOTllY2IxMDc1MjE4NTZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.5kdXv7Qu6BdqDL1Y-Nsoo4oFMzA37jm4OEoKht80I8Q) ](https://private-user-images.githubusercontent.com/187881272/390847002-6a182cd1-ca29-43ef-bd6a-f438b2602d19.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4MTAwNDcsIm5iZiI6MTczMjgwOTc0NywicGF0aCI6Ii8xODc4ODEyNzIvMzkwODQ3MDAyLTZhMTgyY2QxLWNhMjktNDNlZi1iZDZhLWY0MzhiMjYwMmQxOS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOFQxNjAyMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMmYyOGM2YmVmM2ZlZmRkYmYxMWY5OWE1OGMwYjE0ZmZmYTY2ODk4ZmQ3ZTcyYTFlOTllY2IxMDc1MjE4NTZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.5kdXv7Qu6BdqDL1Y-Nsoo4oFMzA37jm4OEoKht80I8Q)
> >       
> >         [
> >           
> >             ![PixPin_2024-11-28_23-52-03](https://private-user-images.githubusercontent.com/187881272/390847002-6a182cd1-ca29-43ef-bd6a-f438b2602d19.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4MTAwNDcsIm5iZiI6MTczMjgwOTc0NywicGF0aCI6Ii8xODc4ODEyNzIvMzkwODQ3MDAyLTZhMTgyY2QxLWNhMjktNDNlZi1iZDZhLWY0MzhiMjYwMmQxOS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOFQxNjAyMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMmYyOGM2YmVmM2ZlZmRkYmYxMWY5OWE1OGMwYjE0ZmZmYTY2ODk4ZmQ3ZTcyYTFlOTllY2IxMDc1MjE4NTZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.5kdXv7Qu6BdqDL1Y-Nsoo4oFMzA37jm4OEoKht80I8Q)
> >           
> >         ](https://private-user-images.githubusercontent.com/187881272/390847002-6a182cd1-ca29-43ef-bd6a-f438b2602d19.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4MTAwNDcsIm5iZiI6MTczMjgwOTc0NywicGF0aCI6Ii8xODc4ODEyNzIvMzkwODQ3MDAyLTZhMTgyY2QxLWNhMjktNDNlZi1iZDZhLWY0MzhiMjYwMmQxOS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOFQxNjAyMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMmYyOGM2YmVmM2ZlZmRkYmYxMWY5OWE1OGMwYjE0ZmZmYTY2ODk4ZmQ3ZTcyYTFlOTllY2IxMDc1MjE4NTZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.5kdXv7Qu6BdqDL1Y-Nsoo4oFMzA37jm4OEoKht80I8Q)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://private-user-images.githubusercontent.com/187881272/390847002-6a182cd1-ca29-43ef-bd6a-f438b2602d19.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4MTAwNDcsIm5iZiI6MTczMjgwOTc0NywicGF0aCI6Ii8xODc4ODEyNzIvMzkwODQ3MDAyLTZhMTgyY2QxLWNhMjktNDNlZi1iZDZhLWY0MzhiMjYwMmQxOS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOFQxNjAyMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMmYyOGM2YmVmM2ZlZmRkYmYxMWY5OWE1OGMwYjE0ZmZmYTY2ODk4ZmQ3ZTcyYTFlOTllY2IxMDc1MjE4NTZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.5kdXv7Qu6BdqDL1Y-Nsoo4oFMzA37jm4OEoKht80I8Q)
> >         
> >        [ ](https://private-user-images.githubusercontent.com/187881272/390847002-6a182cd1-ca29-43ef-bd6a-f438b2602d19.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4MTAwNDcsIm5iZiI6MTczMjgwOTc0NywicGF0aCI6Ii8xODc4ODEyNzIvMzkwODQ3MDAyLTZhMTgyY2QxLWNhMjktNDNlZi1iZDZhLWY0MzhiMjYwMmQxOS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOFQxNjAyMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMmYyOGM2YmVmM2ZlZmRkYmYxMWY5OWE1OGMwYjE0ZmZmYTY2ODk4ZmQ3ZTcyYTFlOTllY2IxMDc1MjE4NTZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.5kdXv7Qu6BdqDL1Y-Nsoo4oFMzA37jm4OEoKht80I8Q)
> 
> 没有自动打开吗？你开一下开发者模式，看看控制台有没有什么报错之类的信息？

有一个，在使用一段时间后就会出现，重启后又会消失，浏览器端正常
![PixPin_2024-11-29_08-35-18](https://github.com/user-attachments/assets/49768661-08e9-4b0c-8cf5-bd6ffe97e501)
![PixPin_2024-11-29_08-36-55](https://github.com/user-attachments/assets/ab26edf4-35e5-4b4f-ad95-6e564f771485)

**Comment by frostime** [comment]
那几个报错不是插件的报错，你在侧栏调整一下，切换到 siyuan-dailynote-today 看一下有没有报错？
![image](https://github.com/user-attachments/assets/33440c36-9403-40d8-845b-4c165385eb0b)

**Comment by KeeeevinK** [comment]
> 那几个报错不是插件的报错，你在侧栏调整一下，切换到 siyuan-dailynote-today 看一下有没有报错？ ![image](https://private-user-images.githubusercontent.com/27268127/390947318-33440c36-9403-40d8-845b-4c165385eb0b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5MDE0NjcsIm5iZiI6MTczMjkwMTE2NywicGF0aCI6Ii8yNzI2ODEyNy8zOTA5NDczMTgtMzM0NDBjMzYtOTQwMy00MGQ4LTg0NWItNGMxNjUzODVlYjBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDE3MjYwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2ZDYyNmYzYWU1OTBiOTdjNmMwMTY3YWI3Y2I5NGM2N2RkZDA2NzZkYWYwN2ZmYmQ5MjFkMWNkNmY3YTg2ZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NOxh6McL9-EgwmQjQWzIIw_nj1hDd7mdKf_8OXG9xUw)

好像没有报错诶，但是很明显就是没有自动打开
![PixPin_2024-11-30_01-49-05](https://github.com/user-attachments/assets/b56e2f62-85e2-4caa-ace5-9edb32e6762c)

排查了一下，感觉是enhance插件有关
![PixPin_2024-11-30_01-37-25](https://github.com/user-attachments/assets/a672bcbe-0486-4e1f-86aa-fa63542f0add)

**Comment by KeeeevinK** [comment]
@frostime 有办法处理吗？还是我跟增强插件那边反馈

**Comment by frostime** [comment]
> @frostime 有办法处理吗？还是我跟增强插件那边反馈

控制台没有报错信息可以提供参考的话，插件冲突这种事情很难搞的。

每个插件有自己的逻辑，除非一点点实验或者看源代码，否则很难弄。而且 enhance 本身不开源，我自己也没怎么用，想要考实验来解决很麻烦，实在没有精力去弄。

**Comment by KeeeevinK** [comment]
> > @frostime 有办法处理吗？还是我跟增强插件那边反馈
> 
> 控制台没有报错信息可以提供参考的话，插件冲突这种事情很难搞的。
> 
> 每个插件有自己的逻辑，除非一点点实验或者看源代码，否则很难弄。而且 enhance 本身不开源，我自己也没怎么用，想要考实验来解决很麻烦，实在没有精力去弄。

好的了解了，感谢开发者🥰👍
