### ISSUE TITLE
设置了日记所属笔记本，再次打开还是跳转到第一个笔记本

### ISSUE THREAD

**Issue by terwer** [frostime/siyuan-dailynote-today#24]
## 期望行为

设置了笔记本之后，再次打开应该是在设置的笔记本里面新建daily note，而不是获取第一个笔记本

## 实际行为

目前看来，是一直获取第一个笔记本

![image](https://github.com/frostime/siyuan-dailynote-today/assets/3259282/2ca51064-76ca-4fbf-9f4a-c3344ae1ca6b)

上面是已经设置了日记是日记笔记本。

但是重启之后，还是获取的是第一个

![image](https://github.com/frostime/siyuan-dailynote-today/assets/3259282/c19bc21c-4436-4fe9-bf21-ff77c631e502)

**Comment by frostime** [comment]
我想你可能理解有点问题，那个下拉框不是用来选择默认笔记本的。而是用来选择笔记本并在笔记本中创建日记的。

那个「√」符号也不是选择的意思，而是标识哪些笔记本已经创建过日记了。

你完全可以在多个笔记本中创建日记，然后你再次打开下拉框，就会发现这些创建过日记的笔记本前面都会有一个「√」符号。
