### ISSUE TITLE
自动在跨日的时候更新笔记的地址

### ISSUE THREAD

**Issue by SunsetSail** [frostime/siyuan-dailynote-today#30]
应该改成取点击时的时间吧

**Comment by frostime** [comment]
右键点击更新一下全局状态就可以了。

出现这种情况是因为插件需要像思源发出请求来确定今天的日记的路径。但是如果每次使用都向思源发请求，会造成没有意义的开销，所以处于权衡我就只在启动的时候会请求一次。

如果后面跨天的话，就刷新一下全局状态就可以了。

**Comment by frostime** [comment]
所以这就是权衡问题了，我设计的时候觉得大部分情况下，用户都是一天结束后会关掉笔记软件，因此没有做自动更新状态的功能。

如果你觉得有必要，我也可以后面加上这个功能。

**Comment by frostime** [comment]
v1.0.2 版本增加了计时器，在跨日的时候自动更新，请下载后在设置中开启这一功能，看看有没有效果。
