### ISSUE TITLE
多设备时，当天第二个打开的设备，会多新增一个日记

### ISSUE THREAD

**Issue by lunzilunzi** [frostime/siyuan-dailynote-today#87]
大概是插件执行先于同步，以至于在第一台设备写的日记还没同步过来，今天的日记本又新创建了一个

**Comment by frostime** [comment]
这个好像还真不好解决，因为插件加载是在同步之前的，插件在创建日记的时候也不知道未来会不会有同步，更无法知道同步后会不会多出一个日记。

**Comment by lunzilunzi** [comment]
或许可以给D大提api

**Comment by frostime** [comment]
我可以去问问。
https://github.com/siyuan-note/siyuan/issues/8414

**Comment by frostime** [comment]
目前是在刚刚启动的时候，监听首次同步，如果发现有日记冲突就弹出一个提示框

![image](https://github.com/frostime/siyuan-dailynote-today/assets/27268127/f704424b-c87a-4481-b9aa-17028f475c13)

至于合并冲突只能交给用户来了。
